### ISSUE TITLE
Physics: Implement Collision Detection + Reaction

### ISSUE THREAD

**Issue by Khouderchah-Alex** [Khouderchah-Alex/CS130-Game#4]
This change will involve implementing the detection of collisions in the PhysicsSystem and the reaction to collisions (maybe through the event system, although there are other options).

The work involved includes:
- Creating a CollisionComponent and potentially modifying the PhysicsComponent. (Entities with a PhysicsComponent can actually react to collisions. Entities with only a CollisionComponent could be, say, a rock that doesn't move but is still collide-able)
    - Collision shapes must be provided by the CollisionComponent (bounding-box, per-vertex collision, etc)
- Definition of collision events and actions

**Comment by Saikedo** [comment]
I decided to implement Bullet Physics API instead of writing collision code from scratch. This will hopefully provide us with more complex and realistic collisions. Also, this requires a change of physics engine that we were using, so our physics engine should also benefit greatly from this since it uses Bullet Physics now.
